name: deploy dantyli-main
on: 
  push: 
    branches: 
      - master
    paths: 
      - 'dist/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: deploy
        uses: garygrossgarten/github-action-scp@release
        with: 
           rmRemote: true
           local: "dist/"
           password: ${{secrets.TOKEN}}
           host: ${{ secrets.IP }}
           username: ${{ secrets.USER }}
           remote: ${{ secrets.TARGET }}